version: '3.9'

services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - /app/node_modules
      - ./backend:/app    
    environment: 
      - MONGODB_URI=mongodb+srv://husseinyy:husseinyy@cluster0.fhffld3.mongodb.net/mernauth?
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - mongoDb
    restart: always    

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always    
    volumes: 
      - /app/node_modules
      - ./frontend:/app  
    environment: 
      - REACT_APP_BACKEND_URL=/api
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: linuxserver/swag
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    container_name: nginx_mern
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=husseini.hopto.org
      - SUBDOMAINS=www,
      - VALIDATION=http
      - STAGING=false
      - EMAIL=mhmd.husseinyy@gmail.com

volumes: 
  db-volume: