version: '3'

services:
  backend-image:
    image: backend-image
    ports:
      - "5000:5000"
    restart: always

  frontend-image:
    image: frontend-image
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-image
      - frontend-image
