version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      my-network:
        ipv4_address: 172.16.238.10  # Assign a specific IPv4 address
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      my-network:
        ipv4_address: 172.16.238.11  # Assign a specific IPv4 address
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      my-network:
        ipv4_address: 172.16.238.12  # Assign a specific IPv4 address

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
