version: '3.8'

services:
  frontend:
    build: ./services/client
    ports:
      - "80:80"
    depends_on:
      - node-api 
  node-api:
    build: ./services/node
    ports:
      - "5000:5000"