version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./frontend/:/app
      - /app/node_modules
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./backend/:/app
      - /app/node_modules

networks:
  mern-app:
    driver: bridge
